
CREATE OR REPLACE PROCEDURE NOWY_KLIENT AS 
BEGIN
  INSERT INTO KLIENCI
  VALUES('88888', '8888', '88888', '88888', '88888');
  przenoszenie;
END NOWY_KLIENT;

/

EXEC NOWY_KLIENT('696969','54312','MIKOLAJ','SIERDZKI','987654321');

/

SELECT * FROM KLIENCI K FULL JOIN promocje p ON K.ID_KLIENTA = p.ID_KLIENTA1

/
SELECT * FROM PROMOCJE P JOIN ZAMOWIENIE Z ON Z.ID_KLIENTA=P.ID_KLIENTA1

/
SELECT * FROM ZAMOWIENIE
/
CREATE OR REPLACE TRIGGER TRIGGER_PROMOCJE
AFTER UPDATE ON ZAMOWIENIE
FOR EACH ROW
BEGIN
    UPDATE PROMOCJE
    SET ILOSC_ZAMOWIEN = 
    (SELECT COUNT(Z.ID_KLIENTA) FROM ZAMOWIENIE Z JOIN KLIENCI K ON Z.ID_KLIENTA =K.ID_KLIENTA JOIN PROMOCJE P ON P.ID_KLIENTA1=K.ID_KLIENTA WHERE K.ID_KLIENTA=Z.ID_KLIENTA GROUP BY Z.ID_KLIENTA);
END;
/

insert into zamowienie
values ('ABC123', '696969', '1233333', '12033333');
/
insert into pracownicy
values ('4627','WITEK','MIKOLAJCZAK','795636494','SKRZYPACZDAWID@GMAIL.COM',NULL,'KIEROWCA')
/
INSERT INTO KIEROWCY
VALUES('4627','6969')
/
INSERT INTO AUTA
VALUES ('ABC123','6969','KIA','RIO','1234321','1')

/

SELECT * FROM ZAMOWIENIE

/

CREATE OR REPLACE PROCEDURE ILOSC_ZAMOWIEN AS
BEGIN
UPDATE PROMOCJE SET ILOSC_ZAMOWIEN = (SELECT COUNT(Z.ID_KLIENTA)  FROM ZAMOWIENIE Z JOIN PROMOCJE P ON Z.ID_KLIENTA=P.ID_KLIENTA1 WHERE ID_KLIENTA1= 696969 GROUP BY Z.ID_KLIENTA);
END ILOSC_ZAMOWIEN;

/

EXEC ILOSC_ZAMOWIEN;

/

ROLLBACK